fieldLayouts:
  6d291fe3-7d5c-407a-a1b9-7277b4185cf6:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Conteúdo
        sortOrder: 1
handle: imagem
hasUrls: true
name: Imagem
settings:
  path: imagens
sortOrder: 1
type: craft\volumes\Local
url: '@web/imagens'
