contentColumnType: text
fieldGroup: b11694b1-64e2-467d-9a30-3b24d1f317ef
handle: valores
instructions: ''
name: Valores
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
