enableVersioning: true
handle: servicos
name: Serviços
propagationMethod: all
siteSettings:
  a13c9432-2932-4d9d-bc96-97075214c98a:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'servicos/{slug}'
type: channel
